var afterQuotes = [
  "There's only one word to describe football, and that's 'if only'.",
  "The lad just lacks a bit of inconsistency.",
  "I didn't say them things I said.",
  "They're having a bad run; they've lost six matches in a row without winning.",
  "It's one of the greatest goals ever, but I'm surprised that people are talking about it being the goal of the season.",
  "At least it was a victory, and at least we won.",
  "We lost because we didn't win.",
  "What I said to them at half-time would be unprintable on the radio.",
  "When you are 4-0 up, you should never lose 7-1.",
  "If you closed your eyes, you couldn't tell the difference between the two sides.",
  "It's thrown a spanner in the fire.",
  "I can count on the fingers of one hand ten games where we've caused our own downfall.",
  "In terms of the Richter scale, this was a Force 8 gale.",
  "Our first goal was pure textile.",
  "We threw our dice into the ring and turned up trumps.",
  "We must have had 99% of the game. It was the other 3% that cost us the match.",
  "I felt a lump in my mouth as the ball went in",
  "Although we are playing Russian Roulette we are obviously playing Catch 22 at the moment and it's a difficult scenario to get my head around.",
  "well actually we got the winner there with three minutes to go, but then they equalised.",
  "I have a number of alternatives and each one gives me something different.",
  "They've picked their heads up off the ground, and they now have a lot to carry on their shoulders.",
  "If history repeats itself, I should think we can expect the same thing again.",
  "This was the game that put the team's ship back on the road.",
  "Football's football: if that weren't the case it wouldn't be the game that it is.",
  "You either win or you lose. There's no in between.",
  "If you take away their five goals, there was nothing between the teams.",
  "It was really difficult for us, playing in the midday sun with that three o'clock kick-off.",
  "Well, it's all about the two 'M's - movement and positioning.",
  "It was 1-1, an exact reversal of the score on Saturday.",
  "We were a little bit outnumbered there, it was two against two.",
  "We thrashed them 0-0 in the first half.",
  "They've won 66 games, and they've scored in all of them.",
  "They forced them into a lot of unforced errors.",
];
