var commentatorQuotes = [
  "For those of you watching in black and white, the home team are in the yellow strip.",
  "I'd be surprised if all twenty-two players are on the field at the end of the game - one's been sent off already.",
  "They're now playing with a five-man back four.",
  "If Plan A fails, he could always revert to Plan A.",
  "...and for those of you watching without televsion sets, live commentary is on Radio Two.",
  "...so different from the scenes in eighteen seventy-two, at the cup final none of us can remember.",
  "It's all end to end stuff, but unfortunately it's all up at this end.",
  "He had an eternity to play that ball, but he took too long over it.",
  "They're the second best team in the world, and there's no higher praise than that.",
  "Not many players get three cracks of the cherry.",
  "This team are now hitting the ropes running.",
  "He went down a bit theoretically then.",
  "You need to take off your rose-scented glasses.",
  "He's just thrown his head in there and it's just come off.",
  "The offside flag went up immediately, if not before.",
  "He's gone down like he's been felled by a tree.",
  "If they can beat this team again, it'll be a good scalpel.",
  "This team aren't as good as they used to be, or as they are now.",
  "He just got his body between himself and the goal.",
  "If there's a weakness in this team's defence, it's in their defence.",
  "As we say in football, it''ll go down to the last wire.",
  "For such a small man, he gets great elevation on his balls.",
  "The lad got overexcited when he saw the whites of the goalpost's eyes.",
  "He's pulling him off! The manager is pulling his captain off.",
  "That was only a yard away from being an inch-perfect pass.",
  "I'd love to be a mole on the wall in the dressing room at half-time.",
  "It's headed away by the defender, using his head.",
  "The players are losing no time in making a meal around the referee.",
  "The ball goes down the keepers throat where it hits him on the knees to say the least.",
  "This team are so good it's like they are running around the pitch playing with themselves.",
  "Their defence is skating close to the wind.",
  "He's got a knock on his shin there, just above the knee.",
  "Their manager is standing on the touchline with his hands in his tracksuit bottoms scratching his head.",
  "Strangely, in slow motion replay, the ball seemed to hang in the air for even longer.",
  "He sends an inch-perfect pass to no one in particular.",
];
